ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS sync_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS sync_webhook_url TEXT;

ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS sync_hmac_secret TEXT;
